### ISSUE TITLE
Company Name for app? 

### ISSUE THREAD

**Issue by tongclement** [Jaosrikate/iBeacon#3]
Is it .BeaconDemoApplication?
Many thanks

**Comment by Jaosrikate** [comment]
App's Name is **BeaconDemoApplication** -> Name of Application class.
The label and App's name in device is **iBeaconDemo**

` <application
        android:name=".BeaconDemoApplication"
        android:label="iBeaconDemo"
</application>`

package name is **com.example.srikate.ibeacondemo**
