### ISSUE TITLE
Execution failed for task ':app:processDebugGoogleServices'.

### ISSUE THREAD

**Issue by skabirgithub** [Jaosrikate/iBeacon#4]
Executing tasks: [:app:assembleDebug] in project C:\Users\skabi\AndroidStudioProjects\beacon\android native\iBeacon-Android-master

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:javaPreCompileDebug
> Task :app:mainApkListPersistenceDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\skabi\AndroidStudioProjects\beacon\android native\iBeacon-Android-master\app\src\nullnull\google-services.json
  C:\Users\skabi\AndroidStudioProjects\beacon\android native\iBeacon-Android-master\app\src\debug\google-services.json
  C:\Users\skabi\AndroidStudioProjects\beacon\android native\iBeacon-Android-master\app\src\nullnullDebug\google-services.json
  C:\Users\skabi\AndroidStudioProjects\beacon\android native\iBeacon-Android-master\app\src\nullnull\debug\google-services.json
  C:\Users\skabi\AndroidStudioProjects\beacon\android native\iBeacon-Android-master\app\src\debug\nullnull\google-services.json
  C:\Users\skabi\AndroidStudioProjects\beacon\android native\iBeacon-Android-master\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
5 actionable tasks: 5 executed

**Comment by Jaosrikate** [comment]
Sorry for my mistake.

> Delete line 45 in app/build.gradle file.
apply plugin: 'com.google.gms.google-services'

It will solve this build exception
Thanks for report
